[[redirects]]
  from = "/admin/home/"
  to = "/admin/"
  status = 401
  conditions = { name = "jwt", op = "eq", value = "" }
[functions]
  external_node_modules = ["jsonwebtoken", "mongodb"]
  node_bundler = "esbuild"